project_id = "yslheyzbhujozyoimihw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_connections = 100
max_channels_per_client = 100
max_joins_per_second = 100
max_events_per_second = 100
postgres_changes_listen_interval = 100

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions.send-invitation]
verify_jwt = false

[functions.database-backup]
verify_jwt = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://lovable.dev", "http://127.0.0.1:5173/tienda/*"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true