// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yslheyzbhujozyoimihw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbGhleXpiaHVqb3p5b2ltaWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjYwMjksImV4cCI6MjA2NTk0MjAyOX0.Pprc_-0XYC0Bh0cLAppkhs3Dbd2O-asXiFVGX6lAUgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);